### ISSUE TITLE
not working.

### ISSUE THREAD

**Issue by hirockstar** [bedimcode/responsive-portfolio-website-Ansel#1]
getting white screen while opeing it.

**Comment by Khaan25** [comment]
It will be white because it is blank...
You have to write the code...

**Comment by VaibhavAswal** [comment]
this is just a base to start from scratch not a final built project

**Comment by hirockstar** [comment]
how to fix it then?

**Comment by krylovDev** [comment]
> how to fix it then?

- [ ] Buy the author some coffee ;)

**Comment by sahan-madusha** [comment]
getting white screen while opening it. how to fix it ?

**Comment by minervasm** [comment]
I'm dying
